// ─── Redis Types ─────────────────────────────────────────────────────────────

export interface StreamMessage {
  /** Stream message ID (auto-generated by Redis) */
  id: string;
  /** Key-value fields in the message */
  fields: Record<string, string>;
}

export interface ConsumerGroup {
  /** Consumer group name */
  name: string;
  /** Stream key this group reads from */
  stream: string;
  /** Last delivered message ID */
  lastDeliveredId: string;
  /** Number of pending (unacknowledged) messages */
  pendingCount: number;
  /** Active consumers in this group */
  consumers: ConsumerInfo[];
}

export interface ConsumerInfo {
  /** Consumer name */
  name: string;
  /** Number of pending messages for this consumer */
  pendingCount: number;
  /** Idle time in ms */
  idleMs: number;
}

export interface StreamConfig {
  /** Stream key (e.g. "hcom:messages") */
  stream: string;
  /** Consumer group name */
  group: string;
  /** Consumer name within the group */
  consumer: string;
  /** Max messages per read (default: 10) */
  count?: number;
  /** Block timeout in ms (default: 5000) */
  blockMs?: number;
  /** Max stream length (approximate) — triggers trimming */
  maxLen?: number;
  /** Minimum idle time in ms for XAUTOCLAIM */
  minIdleMs?: number;
}
